name: "GitHub Actions Workflow Unit Tests"
on:
  push:
    branches:
      - actions

jobs:
  # unit tests
  units:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./brew-universalinstall
      with:
        packages: 'qt:cmake:ninja'
    - uses: ./build-project
      with:
        project: 'vicr123/libcontemporary'
