name: "GitHub Actions Workflow Unit Tests"
on:
  push:
    branches:
      - actions

jobs:
  # unit tests
  units:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./brew-universalinstall
      with:
        packages: 'qt'
